name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - master  # Set this to the branch name you use as your default branch

jobs:
  build_and_deploy:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CYBER_VAL_CLOUD }}'
          projectId: cyber-val-cloud


